# Run services for localdevelopment.
services:
  # Nginx
  web:
    image: "lisitsynalex/investment/web"
    ports:
      - 80:80
  # Backend
  gateway:
    image: "lisitsynalex/investment/gateway"
    environment:
      - PORT=8080
      - USER_SERVICE_HOST=user
      - USER_SERVICE_PORT=9001
  user:
    image: "lisitsynalex/investment/services/user"
    environment:
      - PORT=9001
  # Databases
