# Run services for localdevelopment.
services:
  # Nginx
  nginx:
    image: "lisitsynalex/investment/web"
    ports:
      - 80:80
  # Backend
  gateway:
    image: "lisitsynalex/investment/gateway"
    environment:
      - PORT=8080
      - USER_SERVICE_HOST=users
  user:
    image: "lisitsynalex/investment/services/user"
  # Databases
