openapi: 3.1.0
info:
  version: '1.0'
  title: API for Investment WebApp
  summary: Only for web application
  description: ''
servers:
  - url: 'http://localhost:9090'
    description: ''
paths:
  /portfolios:
    post:
      summary: Create portfolio
      description: Creates new portfolio.
      operationId: post-portolios
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                from:
                  type: string
                to:
                  type: string
      responses: {}
      x-internal: false
    get:
      summary: Get portfolios
      description: Returns all portfolios.
      operationId: get-portolios
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    from:
                      type: string
                    to:
                      type: string
  '/portfolios/{id}':
    get:
      summary: Get portfolio
      description: Returns portfolio.
      operationId: get-portfolios-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses: {}
      servers:
        - url: 'http://localhost:9090'
          description: ''
    put:
      summary: Update portfolio
      description: Updates portfolio.
      operationId: put-portfolios-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses: {}
      servers:
        - url: 'http://localhost:9090'
          description: ''
    delete:
      summary: Delete portfolio
      description: Deletes portfolio.
      operationId: delete-portfolios-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses: {}
      servers:
        - url: 'http://localhost:9090'
          description: ''
x-internal: false
